Allow environment variables to be overwritten
This should be harmless and will hopefully fix an unexplained problem
where some requests for /debug_kit/js/*.js files would sometimes return
this response:

Fatal error: Uncaught LogicException: Key "APP_NAME" has already been defined in getenv() in C:\xampp\htdocs\muncie_events3\vendor\josegonzalez\dotenv\src\josegonzalez\Dotenv\Loader.php on line 434

1	0.0011	366272	{main}( )				...\index.php:0
2	0.0394	1803712	Cake\Http\Server->run( )		...\index.php:40
3	0.0394	1803712	Cake\Http\Server->bootstrap( )		...\Server.php:82
4	0.0394	1803712	App\Application->bootstrap( )		...\Server.php:121
5	0.0394	1803712	App\Application->bootstrap( )		...\Application.php:41
6	0.0401	1828232	require_once( 'C:\xampp\htdocs\muncie_events3\config\bootstrap.php' )	...\BaseApplication.php:152
7	0.0543	2254464	josegonzalez\Dotenv\Loader->putenv( )	...\bootstrap.php:57
8	0.0543	2254784	josegonzalez\Dotenv\Loader->raise( )	...\Loader.php:291

This error doesn't make sense to me, since the .env-loading code is
wrapped in if(!env('APP_NAME')). Maybe something's running in parallel
and there's a race condition? That might explain why these requests seem
to either work or not work arbitrarily, even when hitting refresh on the
same page.